<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSysPermissionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {

        Schema::create('sys_permissions', function (Blueprint $table) {
            $table->smallIncrements('id');
            $table->smallInteger('parent_id')->comment('父级id');
            $table->string('path', 128)->comment('路由路径');
            $table->string('name', 56)->comment('权限名称');
            $table->string('icon', 32)->comment('图标');
            $table->tinyInteger('is_display')->default(1)->comment('是否显示');

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('sys_permissions');
    }
}
