<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSysPermissionsUserTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {


        Schema::create('sys_permissions_user', function (Blueprint $table) {
            $table->increments('id');
            $table->smallInteger('permission_id')->comment('权限id');
            $table->smallInteger('u_id')->comment('用户id');
            $table->tinyInteger('modify')->default(1)->comment('修改权限');
            $table->tinyInteger('remove')->default(1)->comment('删除权限');
            $table->tinyInteger('create')->default(1)->comment('创建权限');

            $table->index('u_id', 'u_id');

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('sys_permissions_user');
    }
}
